-- V1__init_core.sql
-- EquipRent — núcleo físico: categoria_equipo -> equipo -> unidad_equipo, cliente, reserva
-- Orden de ejecución respeta dependencias por FK.

-- 1. categoria_equipo (raíz de catálogo, sin FK)
CREATE TABLE categoria_equipo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(20) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    CONSTRAINT uq_categoria_equipo_codigo UNIQUE (codigo),
    CONSTRAINT ck_categoria_equipo_codigo CHECK (BTRIM(codigo) <> '')
);

-- 2. equipo (depende de categoria_equipo)
CREATE TABLE equipo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_equipo_id BIGINT NOT NULL,
    codigo_modelo VARCHAR(30) NOT NULL,
    nombre VARCHAR(120) NOT NULL,
    marca VARCHAR(60),
    tarifa_dia NUMERIC(10,2) NOT NULL,
    CONSTRAINT fk_equipo_categoria
        FOREIGN KEY (categoria_equipo_id) REFERENCES categoria_equipo(id),
    CONSTRAINT uq_equipo_codigo_modelo UNIQUE (codigo_modelo),
    CONSTRAINT ck_equipo_tarifa_dia CHECK (tarifa_dia > 0)
);

-- 3. unidad_equipo (depende de equipo)
CREATE TABLE unidad_equipo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    equipo_id BIGINT NOT NULL,
    codigo_inventario VARCHAR(30) NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'DISPONIBLE',
    fecha_adquisicion DATE,
    CONSTRAINT fk_unidad_equipo_equipo
        FOREIGN KEY (equipo_id) REFERENCES equipo(id),
    CONSTRAINT uq_unidad_equipo_codigo_inventario UNIQUE (codigo_inventario),
    CONSTRAINT ck_unidad_equipo_estado
        CHECK (estado IN ('DISPONIBLE', 'RESERVADA', 'ALQUILADA', 'EN_MANTENIMIENTO', 'DE_BAJA'))
);

-- 4. cliente (raíz de actor, sin FK)
CREATE TABLE cliente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_completo VARCHAR(150) NOT NULL,
    documento_identidad VARCHAR(20) NOT NULL,
    telefono VARCHAR(20),
    email VARCHAR(120),
    CONSTRAINT uq_cliente_documento_identidad UNIQUE (documento_identidad),
    CONSTRAINT uq_cliente_email UNIQUE (email)
);

-- 5. reserva (depende de cliente y de unidad_equipo)
CREATE TABLE reserva (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT NOT NULL,
    unidad_equipo_id BIGINT NOT NULL,
    fecha_inicio TIMESTAMPTZ NOT NULL,
    fecha_fin TIMESTAMPTZ NOT NULL,
    estado VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    deposito NUMERIC(10,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reserva_cliente
        FOREIGN KEY (cliente_id) REFERENCES cliente(id),
    CONSTRAINT fk_reserva_unidad_equipo
        FOREIGN KEY (unidad_equipo_id) REFERENCES unidad_equipo(id),
    CONSTRAINT ck_reserva_fechas CHECK (fecha_fin > fecha_inicio),
    CONSTRAINT ck_reserva_estado
        CHECK (estado IN ('PENDIENTE', 'CONFIRMADA', 'CANCELADA', 'COMPLETADA')),
    CONSTRAINT ck_reserva_deposito CHECK (deposito >= 0)
);

-- Dataset mínimo válido por tabla núcleo (Paso 7 de la guía)
INSERT INTO categoria_equipo (codigo, nombre, descripcion)
VALUES ('CAT-01', 'Herramientas eléctricas', 'Taladros, amoladoras y equipo eléctrico portátil');

INSERT INTO equipo (categoria_equipo_id, codigo_modelo, nombre, marca, tarifa_dia)
VALUES (1, 'EQ-TAL-001', 'Taladro percutor', 'Bosch', 45.00);

INSERT INTO unidad_equipo (equipo_id, codigo_inventario, estado, fecha_adquisicion)
VALUES (1, 'INV-000123', 'DISPONIBLE', '2025-02-10');

INSERT INTO cliente (nombre_completo, documento_identidad, telefono, email)
VALUES ('Marco Antonio Fernández', '7654321', '70011223', 'marco.fernandez@example.com');

INSERT INTO reserva (cliente_id, unidad_equipo_id, fecha_inicio, fecha_fin, estado, deposito)
VALUES (1, 1, '2026-09-01 08:00:00-04', '2026-09-03 18:00:00-04', 'PENDIENTE', 100.00);

SELECT * FROM categoria_equipo;
SELECT * FROM equipo;
SELECT * FROM unidad_equipo;
SELECT * FROM cliente;
SELECT * FROM reserva;

-- Pruebas de integridad sugeridas (ejecutar manualmente, NO dejar aplicadas en V1):
-- 1) NOT NULL:   INSERT INTO cliente (nombre_completo, documento_identidad) VALUES (NULL, '123');
-- 2) UNIQUE:     INSERT INTO categoria_equipo (codigo, nombre) VALUES ('CAT-01', 'Duplicado');
-- 3) FOREIGN KEY: INSERT INTO equipo (categoria_equipo_id, codigo_modelo, nombre, tarifa_dia)
--                 VALUES (999, 'EQ-FAKE', 'Equipo inexistente', 10.00);
-- 4) CHECK:      INSERT INTO unidad_equipo (equipo_id, codigo_inventario, estado)
--                VALUES (1, 'INV-999', 'ESTADO_INVALIDO');
