-- =====================================================================
-- EquipRent · V1 · Creación completa del esquema PostgreSQL
-- Proyecto 15 · Programación Aplicada 2026-2
-- Ejecutar conectado como: equiprent_admin / base equiprent
-- Crea el schema "equiprent" con 18 tablas.
-- Orden de creación respetando dependencias (Clase 05, Paso 12).
-- =====================================================================

SELECT current_user AS usuario_actual, current_database() AS base_actual;

CREATE SCHEMA IF NOT EXISTS equiprent;
SET search_path TO equiprent, public;

-- ---------------------------------------------------------------------
-- BLOQUE A · Identidad y roles
-- ---------------------------------------------------------------------

-- 1. usuario
CREATE TABLE usuario (
    usuario_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username         VARCHAR(60)  NOT NULL,
    email            VARCHAR(160) NOT NULL,
    password_hash    VARCHAR(255) NOT NULL,
    nombre_completo  VARCHAR(160) NOT NULL,
    activo           BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_usuario PRIMARY KEY (usuario_id),
    CONSTRAINT uq_usuario_username UNIQUE (username),
    CONSTRAINT uq_usuario_email UNIQUE (email),
    CONSTRAINT ck_usuario_username_no_vacio CHECK (btrim(username) <> '')
);

-- 2. rol
CREATE TABLE rol (
    rol_id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    codigo       VARCHAR(40)  NOT NULL,
    nombre       VARCHAR(100) NOT NULL,
    descripcion  TEXT         NULL,
    activo       BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_rol PRIMARY KEY (rol_id),
    CONSTRAINT uq_rol_codigo UNIQUE (codigo),
    CONSTRAINT ck_rol_codigo CHECK (codigo IN
        ('ADMINISTRADOR','OPERADOR','TECNICO','CLIENTE','SUPERVISOR'))
);

-- 3. usuario_rol (puente N:M usuario <-> rol)
CREATE TABLE usuario_rol (
    usuario_rol_id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id      BIGINT      NOT NULL,
    rol_id          BIGINT      NOT NULL,
    asignado_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    activo          BOOLEAN     NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_usuario_rol PRIMARY KEY (usuario_rol_id),
    CONSTRAINT fk_usuario_rol_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (usuario_id),
    CONSTRAINT fk_usuario_rol_rol     FOREIGN KEY (rol_id)     REFERENCES rol (rol_id),
    CONSTRAINT uq_usuario_rol UNIQUE (usuario_id, rol_id)
);

-- ---------------------------------------------------------------------
-- BLOQUE B · Clientes
-- ---------------------------------------------------------------------

-- 4. cliente
CREATE TABLE cliente (
    cliente_id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id        BIGINT       NULL,          -- cuenta móvil opcional
    numero_documento  VARCHAR(30)  NOT NULL,
    nombre_completo   VARCHAR(160) NOT NULL,
    email             VARCHAR(160) NULL,
    telefono          VARCHAR(30)  NULL,
    direccion         VARCHAR(220) NULL,
    activo            BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_cliente PRIMARY KEY (cliente_id),
    CONSTRAINT fk_cliente_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (usuario_id),
    CONSTRAINT uq_cliente_documento UNIQUE (numero_documento),
    CONSTRAINT uq_cliente_email UNIQUE (email),
    CONSTRAINT uq_cliente_usuario UNIQUE (usuario_id),
    CONSTRAINT ck_cliente_documento_no_vacio CHECK (btrim(numero_documento) <> '')
);

-- ---------------------------------------------------------------------
-- BLOQUE C · Catálogo y activos (núcleo de los capítulos 01-07)
-- ---------------------------------------------------------------------

-- 5. categoria_equipo
CREATE TABLE categoria_equipo (
    categoria_id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    codigo        VARCHAR(30)  NOT NULL,
    nombre        VARCHAR(100) NOT NULL,
    descripcion   TEXT         NULL,
    activo        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_categoria_equipo PRIMARY KEY (categoria_id),
    CONSTRAINT uq_categoria_equipo_codigo UNIQUE (codigo)
);

-- 6. equipo  (ENTIDAD PADRE del par 1:N)
CREATE TABLE equipo (
    equipo_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    categoria_id  BIGINT       NOT NULL,
    codigo        VARCHAR(30)  NOT NULL,
    nombre        VARCHAR(120) NOT NULL,
    marca         VARCHAR(60)  NULL,
    modelo        VARCHAR(60)  NULL,
    descripcion   TEXT         NULL,
    activo        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_equipo PRIMARY KEY (equipo_id),
    CONSTRAINT fk_equipo_categoria FOREIGN KEY (categoria_id) REFERENCES categoria_equipo (categoria_id),
    CONSTRAINT uq_equipo_codigo UNIQUE (codigo),
    CONSTRAINT ck_equipo_codigo_no_vacio CHECK (btrim(codigo) <> '')
);

-- 7. unidad_equipo  (ENTIDAD DEPENDIENTE del par 1:N) · RN-01
CREATE TABLE unidad_equipo (
    unidad_id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    equipo_id          BIGINT        NOT NULL,
    codigo_unidad      VARCHAR(40)   NOT NULL,
    numero_serie       VARCHAR(80)   NULL,
    estado             VARCHAR(20)   NOT NULL DEFAULT 'DISPONIBLE',
    fecha_adquisicion  DATE          NULL,
    valor_referencial  NUMERIC(12,2) NULL,
    observacion        TEXT          NULL,
    created_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT pk_unidad_equipo PRIMARY KEY (unidad_id),
    CONSTRAINT fk_unidad_equipo_equipo FOREIGN KEY (equipo_id) REFERENCES equipo (equipo_id),
    CONSTRAINT uq_unidad_equipo_codigo UNIQUE (codigo_unidad),
    CONSTRAINT uq_unidad_equipo_serie UNIQUE (numero_serie),
    CONSTRAINT ck_unidad_equipo_estado CHECK (estado IN
        ('DISPONIBLE','ENTREGADA','EN_INSPECCION','MANTENIMIENTO','BLOQUEADA','BAJA')),
    CONSTRAINT ck_unidad_equipo_valor CHECK (valor_referencial IS NULL OR valor_referencial >= 0),
    CONSTRAINT ck_unidad_equipo_codigo_no_vacio CHECK (btrim(codigo_unidad) <> '')
);

-- 8. tarifa
CREATE TABLE tarifa (
    tarifa_id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    equipo_id          BIGINT        NOT NULL,
    nombre             VARCHAR(100)  NOT NULL,
    unidad_cobro       VARCHAR(20)   NOT NULL,
    monto              NUMERIC(12,2) NOT NULL,
    deposito_sugerido  NUMERIC(12,2) NULL,
    vigente_desde      DATE          NOT NULL,
    vigente_hasta      DATE          NULL,
    activo             BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_tarifa PRIMARY KEY (tarifa_id),
    CONSTRAINT fk_tarifa_equipo FOREIGN KEY (equipo_id) REFERENCES equipo (equipo_id),
    CONSTRAINT ck_tarifa_unidad CHECK (unidad_cobro IN ('HORA','DIA','SEMANA','MES')),
    CONSTRAINT ck_tarifa_monto CHECK (monto >= 0),
    CONSTRAINT ck_tarifa_deposito CHECK (deposito_sugerido IS NULL OR deposito_sugerido >= 0),
    CONSTRAINT ck_tarifa_vigencia CHECK (vigente_hasta IS NULL OR vigente_hasta >= vigente_desde)
);

-- ---------------------------------------------------------------------
-- BLOQUE D · Flujo transaccional: reserva -> entrega -> devolución
-- ---------------------------------------------------------------------

-- 9. reserva
CREATE TABLE reserva (
    reserva_id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    codigo              VARCHAR(30)  NOT NULL,
    cliente_id          BIGINT       NOT NULL,
    fecha_inicio        TIMESTAMPTZ  NOT NULL,
    fecha_fin           TIMESTAMPTZ  NOT NULL,
    estado              VARCHAR(20)  NOT NULL DEFAULT 'PENDIENTE',
    motivo_cancelacion  TEXT         NULL,
    created_by          BIGINT       NULL,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_reserva PRIMARY KEY (reserva_id),
    CONSTRAINT fk_reserva_cliente FOREIGN KEY (cliente_id) REFERENCES cliente (cliente_id),
    CONSTRAINT fk_reserva_created_by FOREIGN KEY (created_by) REFERENCES usuario (usuario_id),
    CONSTRAINT uq_reserva_codigo UNIQUE (codigo),
    CONSTRAINT ck_reserva_fechas CHECK (fecha_fin > fecha_inicio),
    CONSTRAINT ck_reserva_estado CHECK (estado IN
        ('PENDIENTE','CONFIRMADA','EN_CURSO','FINALIZADA','CANCELADA')),
    CONSTRAINT ck_reserva_motivo_cancelacion CHECK
        (estado <> 'CANCELADA' OR motivo_cancelacion IS NOT NULL)
);

-- 10. reserva_detalle (puente N:M reserva <-> unidad_equipo)
CREATE TABLE reserva_detalle (
    reserva_detalle_id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    reserva_id          BIGINT        NOT NULL,
    unidad_id           BIGINT        NOT NULL,
    tarifa_id           BIGINT        NULL,
    precio_aplicado     NUMERIC(12,2) NOT NULL,
    CONSTRAINT pk_reserva_detalle PRIMARY KEY (reserva_detalle_id),
    CONSTRAINT fk_reserva_detalle_reserva FOREIGN KEY (reserva_id) REFERENCES reserva (reserva_id),
    CONSTRAINT fk_reserva_detalle_unidad  FOREIGN KEY (unidad_id)  REFERENCES unidad_equipo (unidad_id),
    CONSTRAINT fk_reserva_detalle_tarifa  FOREIGN KEY (tarifa_id)  REFERENCES tarifa (tarifa_id),
    CONSTRAINT uq_reserva_detalle UNIQUE (reserva_id, unidad_id),
    CONSTRAINT ck_reserva_detalle_precio CHECK (precio_aplicado >= 0)
);

-- 11. entrega (1:0..1 con reserva) · RN-04, RN-05
CREATE TABLE entrega (
    entrega_id                BIGINT GENERATED BY DEFAULT AS IDENTITY,
    reserva_id                BIGINT      NOT NULL,
    entregado_por             BIGINT      NULL,
    entregado_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    autorizacion_excepcional  BOOLEAN     NOT NULL DEFAULT FALSE,
    autorizado_por            BIGINT      NULL,
    observacion               TEXT        NULL,
    CONSTRAINT pk_entrega PRIMARY KEY (entrega_id),
    CONSTRAINT fk_entrega_reserva FOREIGN KEY (reserva_id) REFERENCES reserva (reserva_id),
    CONSTRAINT fk_entrega_entregado_por FOREIGN KEY (entregado_por) REFERENCES usuario (usuario_id),
    CONSTRAINT fk_entrega_autorizado_por FOREIGN KEY (autorizado_por) REFERENCES usuario (usuario_id),
    CONSTRAINT uq_entrega_reserva UNIQUE (reserva_id),
    CONSTRAINT ck_entrega_autorizacion CHECK
        (autorizacion_excepcional = FALSE OR autorizado_por IS NOT NULL)
);

-- 12. deposito · RN-08 (operativo, sin pasarela)
CREATE TABLE deposito (
    deposito_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    reserva_id      BIGINT        NOT NULL,
    monto           NUMERIC(12,2) NOT NULL,
    metodo          VARCHAR(20)   NOT NULL,
    estado          VARCHAR(20)   NOT NULL DEFAULT 'RETENIDO',
    referencia      VARCHAR(100)  NULL,
    registrado_por  BIGINT        NULL,
    registrado_at   TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT pk_deposito PRIMARY KEY (deposito_id),
    CONSTRAINT fk_deposito_reserva FOREIGN KEY (reserva_id) REFERENCES reserva (reserva_id),
    CONSTRAINT fk_deposito_registrado_por FOREIGN KEY (registrado_por) REFERENCES usuario (usuario_id),
    CONSTRAINT ck_deposito_monto CHECK (monto > 0),
    CONSTRAINT ck_deposito_metodo CHECK (metodo IN ('EFECTIVO','QR','TRANSFERENCIA','TARJETA')),
    CONSTRAINT ck_deposito_estado CHECK (estado IN ('RETENIDO','DEVUELTO','APLICADO_A_DANO'))
);

-- 13. devolucion (1:0..1 con reserva) · RN-06
CREATE TABLE devolucion (
    devolucion_id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    reserva_id     BIGINT      NOT NULL,
    recibido_por   BIGINT      NULL,
    devuelto_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    observacion    TEXT        NULL,
    CONSTRAINT pk_devolucion PRIMARY KEY (devolucion_id),
    CONSTRAINT fk_devolucion_reserva FOREIGN KEY (reserva_id) REFERENCES reserva (reserva_id),
    CONSTRAINT fk_devolucion_recibido_por FOREIGN KEY (recibido_por) REFERENCES usuario (usuario_id),
    CONSTRAINT uq_devolucion_reserva UNIQUE (reserva_id)
);

-- ---------------------------------------------------------------------
-- BLOQUE E · Inspección, daños y mantenimiento
-- ---------------------------------------------------------------------

-- 14. inspeccion
CREATE TABLE inspeccion (
    inspeccion_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    devolucion_id     BIGINT      NULL,   -- NULL = inspección fuera de una devolución
    unidad_id         BIGINT      NOT NULL,
    tecnico_id        BIGINT      NULL,
    condicion         VARCHAR(20) NOT NULL,
    observacion       TEXT        NULL,
    inspeccionado_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_inspeccion PRIMARY KEY (inspeccion_id),
    CONSTRAINT fk_inspeccion_devolucion FOREIGN KEY (devolucion_id) REFERENCES devolucion (devolucion_id),
    CONSTRAINT fk_inspeccion_unidad FOREIGN KEY (unidad_id) REFERENCES unidad_equipo (unidad_id),
    CONSTRAINT fk_inspeccion_tecnico FOREIGN KEY (tecnico_id) REFERENCES usuario (usuario_id),
    CONSTRAINT uq_inspeccion_devolucion_unidad UNIQUE (devolucion_id, unidad_id),
    CONSTRAINT ck_inspeccion_condicion CHECK (condicion IN ('BUENA','DESGASTE','DANADA','INOPERATIVA'))
);

-- 15. dano · RN-07
CREATE TABLE dano (
    dano_id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    unidad_id        BIGINT        NOT NULL,
    inspeccion_id    BIGINT        NULL,
    descripcion      TEXT          NOT NULL,
    severidad        VARCHAR(20)   NOT NULL,
    bloquea_unidad   BOOLEAN       NOT NULL DEFAULT FALSE,
    costo_estimado   NUMERIC(12,2) NULL,
    estado           VARCHAR(20)   NOT NULL DEFAULT 'REGISTRADO',
    registrado_por   BIGINT        NULL,
    registrado_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT pk_dano PRIMARY KEY (dano_id),
    CONSTRAINT fk_dano_unidad FOREIGN KEY (unidad_id) REFERENCES unidad_equipo (unidad_id),
    CONSTRAINT fk_dano_inspeccion FOREIGN KEY (inspeccion_id) REFERENCES inspeccion (inspeccion_id),
    CONSTRAINT fk_dano_registrado_por FOREIGN KEY (registrado_por) REFERENCES usuario (usuario_id),
    CONSTRAINT ck_dano_severidad CHECK (severidad IN ('LEVE','MODERADO','GRAVE')),
    CONSTRAINT ck_dano_estado CHECK (estado IN ('REGISTRADO','EN_REPARACION','RESUELTO')),
    CONSTRAINT ck_dano_costo CHECK (costo_estimado IS NULL OR costo_estimado >= 0),
    CONSTRAINT ck_dano_descripcion_no_vacia CHECK (btrim(descripcion) <> '')
);

-- 16. mantenimiento
CREATE TABLE mantenimiento (
    mantenimiento_id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    unidad_id         BIGINT        NOT NULL,
    dano_id           BIGINT        NULL,
    tipo              VARCHAR(20)   NOT NULL,
    estado            VARCHAR(20)   NOT NULL DEFAULT 'PROGRAMADO',
    fecha_inicio      TIMESTAMPTZ   NOT NULL,
    fecha_fin         TIMESTAMPTZ   NULL,
    descripcion       TEXT          NULL,
    costo             NUMERIC(12,2) NULL,
    responsable_id    BIGINT        NULL,
    created_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT pk_mantenimiento PRIMARY KEY (mantenimiento_id),
    CONSTRAINT fk_mantenimiento_unidad FOREIGN KEY (unidad_id) REFERENCES unidad_equipo (unidad_id),
    CONSTRAINT fk_mantenimiento_dano FOREIGN KEY (dano_id) REFERENCES dano (dano_id),
    CONSTRAINT fk_mantenimiento_responsable FOREIGN KEY (responsable_id) REFERENCES usuario (usuario_id),
    CONSTRAINT ck_mantenimiento_tipo CHECK (tipo IN ('PREVENTIVO','CORRECTIVO')),
    CONSTRAINT ck_mantenimiento_estado CHECK (estado IN ('PROGRAMADO','EN_PROCESO','FINALIZADO','CANCELADO')),
    CONSTRAINT ck_mantenimiento_fechas CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_inicio),
    CONSTRAINT ck_mantenimiento_costo CHECK (costo IS NULL OR costo >= 0)
);

-- ---------------------------------------------------------------------
-- BLOQUE F · Trazabilidad (RN-10, RF-15, RF-18)
-- ---------------------------------------------------------------------

-- 17. historial_estado_unidad
CREATE TABLE historial_estado_unidad (
    historial_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    unidad_id        BIGINT       NOT NULL,
    estado_anterior  VARCHAR(20)  NULL,   -- NULL en el alta de la unidad
    estado_nuevo     VARCHAR(20)  NOT NULL,
    motivo           VARCHAR(200) NULL,
    cambiado_por     BIGINT       NULL,
    cambiado_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_historial_estado_unidad PRIMARY KEY (historial_id),
    CONSTRAINT fk_historial_unidad FOREIGN KEY (unidad_id) REFERENCES unidad_equipo (unidad_id),
    CONSTRAINT fk_historial_cambiado_por FOREIGN KEY (cambiado_por) REFERENCES usuario (usuario_id),
    CONSTRAINT ck_historial_estado_nuevo CHECK (estado_nuevo IN
        ('DISPONIBLE','ENTREGADA','EN_INSPECCION','MANTENIMIENTO','BLOQUEADA','BAJA')),
    CONSTRAINT ck_historial_estado_anterior CHECK (estado_anterior IS NULL OR estado_anterior IN
        ('DISPONIBLE','ENTREGADA','EN_INSPECCION','MANTENIMIENTO','BLOQUEADA','BAJA'))
);

-- 18. auditoria
CREATE TABLE auditoria (
    auditoria_id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    usuario_id    BIGINT      NULL,
    entidad       VARCHAR(60) NOT NULL,
    entidad_id    BIGINT      NULL,
    accion        VARCHAR(40) NOT NULL,
    es_excepcion  BOOLEAN     NOT NULL DEFAULT FALSE,
    detalle       JSONB       NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_auditoria PRIMARY KEY (auditoria_id),
    CONSTRAINT fk_auditoria_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (usuario_id)
);

-- ---------------------------------------------------------------------
-- RN-10 · El historial del activo no se elimina
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION fn_impedir_borrado_historico()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'RN-10: los registros de % no se pueden eliminar', TG_TABLE_NAME;
END;
$$;

CREATE TRIGGER trg_historial_no_delete
    BEFORE DELETE ON historial_estado_unidad
    FOR EACH ROW EXECUTE FUNCTION fn_impedir_borrado_historico();

CREATE TRIGGER trg_auditoria_no_delete
    BEFORE DELETE ON auditoria
    FOR EACH ROW EXECUTE FUNCTION fn_impedir_borrado_historico();

-- ---------------------------------------------------------------------
-- Índices justificados para consultas relevantes
-- ---------------------------------------------------------------------
CREATE INDEX idx_equipo_categoria            ON equipo (categoria_id);
CREATE INDEX idx_unidad_equipo_equipo        ON unidad_equipo (equipo_id);        -- listar unidades por equipo (Cap. 07)
CREATE INDEX idx_unidad_equipo_estado        ON unidad_equipo (estado);           -- dashboard / disponibilidad
CREATE INDEX idx_tarifa_equipo               ON tarifa (equipo_id);
CREATE INDEX idx_reserva_cliente             ON reserva (cliente_id);             -- RF-16 mis reservas
CREATE INDEX idx_reserva_rango               ON reserva (fecha_inicio, fecha_fin); -- RF-05 / RF-07 solapes
CREATE INDEX idx_reserva_detalle_unidad      ON reserva_detalle (unidad_id);      -- RN-02 conflictos por unidad
CREATE INDEX idx_deposito_reserva            ON deposito (reserva_id);
CREATE INDEX idx_inspeccion_unidad           ON inspeccion (unidad_id);
CREATE INDEX idx_dano_unidad                 ON dano (unidad_id);
CREATE INDEX idx_mantenimiento_unidad        ON mantenimiento (unidad_id);
CREATE INDEX idx_historial_unidad_fecha      ON historial_estado_unidad (unidad_id, cambiado_at); -- RF-15
CREATE INDEX idx_auditoria_entidad           ON auditoria (entidad, entidad_id);

-- Verificación rápida: debe devolver 18
SELECT COUNT(*) AS cantidad_tablas
FROM information_schema.tables
WHERE table_schema = 'equiprent'
  AND table_type = 'BASE TABLE';
